# Generated by Django 3.0.4 on 2020-03-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name_plural': 'Categorias'},
        ),
        migrations.AddField(
            model_name='categoria',
            name='nome',
            field=models.CharField(blank=True, help_text='Nome da categoria', max_length=50, null=True, verbose_name='Nome'),
        ),
    ]
