# Generated by Django 3.0.4 on 2020-03-06 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0002_auto_20200306_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Entidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, help_text='Nome da entidade', max_length=50, null=True, verbose_name='Nome')),
                ('nif', models.CharField(blank=True, help_text='Número de Identificação Fiscal', max_length=50, null=True, verbose_name='NIF')),
                ('tipo', models.CharField(choices=[('F', 'Família'), ('E', 'Empresa'), ('O', 'ONG')], default='F', max_length=1, verbose_name='Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, help_text='Nome da conta', max_length=50, null=True, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('B', 'Banco'), ('C', 'Caixa'), ('L', 'Cliente'), ('P', 'Parceiro')], default='B', max_length=1, verbose_name='Tipo')),
                ('entidade', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='transacoes.Entidade', verbose_name='Entidade')),
            ],
        ),
    ]
