# Generated by Django 3.0.4 on 2020-03-06 19:52

from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0003_banco_conta_entidade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conta',
            options={'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='entidade',
            options={'verbose_name_plural': 'Entidades'},
        ),
        migrations.AddField(
            model_name='transacao',
            name='destino',
            field=models.ForeignKey(default=0, help_text='Inserir a conta de destino', on_delete=django.db.models.deletion.CASCADE, related_name='conta_destino', to='transacoes.Conta', verbose_name='Conta de destino'),
        ),
        migrations.AddField(
            model_name='transacao',
            name='origem',
            field=models.ForeignKey(default=0, help_text='Inserir a conta de origem', on_delete=django.db.models.deletion.CASCADE, related_name='conta_origem', to='transacoes.Conta', verbose_name='Conta de origem'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='tipo',
            field=models.CharField(choices=[('F', 'Família'), ('E', 'Empresa'), ('O', 'ONG')], default='F', help_text='Escolha o tipo de conta', max_length=1, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='Data',
            field=models.DateTimeField(auto_now_add=True, help_text='Data da transação', verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='categoria',
            field=models.ForeignKey(default=0, help_text='Nome da categoria', on_delete=django.db.models.deletion.CASCADE, to='transacoes.Categoria', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='tipo',
            field=models.CharField(choices=[('T', 'Transferência'), ('D', 'Depósito')], default='T', help_text='Escolha o tipo de transação', max_length=1, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='valor',
            field=djmoney.models.fields.MoneyField(decimal_places=4, default_currency='AOA', help_text='Inserir o valor que pretende transacionar', max_digits=19, null=True),
        ),
    ]
