# Generated by Django 3.0.4 on 2020-03-06 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0004_auto_20200306_2052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conta',
            options={'verbose_name_plural': 'Contas'},
        ),
    ]
