# Generated by Django 3.0.4 on 2020-03-07 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0005_auto_20200306_2230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transacao',
            old_name='categoria',
            new_name='id_categoria',
        ),
        migrations.RenameField(
            model_name='transacao',
            old_name='destino',
            new_name='id_destino',
        ),
        migrations.RenameField(
            model_name='transacao',
            old_name='origem',
            new_name='id_origem',
        ),
        migrations.RenameField(
            model_name='transacao',
            old_name='tipo',
            new_name='id_tipo',
        ),
    ]
