# Generated by Django 3.0.4 on 2020-03-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0006_auto_20200307_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='Data',
            field=models.DateTimeField(auto_now_add=True, help_text='Data da transação', null=True, verbose_name='Data'),
        ),
    ]
