# Generated by Django 3.0.4 on 2020-03-07 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0007_auto_20200307_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transacao',
            old_name='Data',
            new_name='data',
        ),
    ]
