# Generated by Django 3.0.4 on 2020-09-09 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0009_auto_20200307_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacao',
            name='valor_currency',
        ),
        migrations.AlterField(
            model_name='transacao',
            name='valor',
            field=models.DecimalField(decimal_places=2, help_text='Inserir o valor que pretende transacionar', max_digits=19, null=True, verbose_name='Valor da transalção'),
        ),
    ]
