# Generated by Django 3.0.4 on 2020-09-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0010_auto_20200909_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='valor',
            field=models.DecimalField(decimal_places=2, help_text='Inserir o valor que pretende transacionar', max_digits=19, null=True, verbose_name='Valor da transação'),
        ),
    ]
