# Generated by Django 3.0.4 on 2020-09-09 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0011_auto_20200909_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='id_categoria',
            field=models.ForeignKey(blank=True, help_text='Nome da categoria', null=True, on_delete=django.db.models.deletion.SET_NULL, to='transacoes.Categoria', verbose_name='Categoria'),
        ),
    ]
