# Generated by Django 3.0.4 on 2020-09-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0012_auto_20200909_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conta',
            old_name='entidade',
            new_name='id_entidade',
        ),
        migrations.RemoveField(
            model_name='entidade',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='conta',
            name='tipo',
            field=models.CharField(choices=[('I', 'Pessoal'), ('L', 'Cliente'), ('P', 'Parceiro'), ('E', 'Empresa'), ('F', 'Fornecedor')], default='I', max_length=1, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='tipo',
            field=models.CharField(choices=[('T', 'Transferência'), ('R', 'Receita'), ('D', 'Despesa')], default='T', help_text='Escolha o tipo de transação', max_length=1, verbose_name='Tipo'),
        ),
    ]
