# Generated by Django 3.0.4 on 2020-09-09 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0013_auto_20200909_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='id_entidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transacoes.Entidade', verbose_name='Entidade'),
        ),
        migrations.AlterField(
            model_name='conta',
            name='tipo',
            field=models.CharField(choices=[('I', 'Pessoal'), ('L', 'Cliente'), ('P', 'Parceiro'), ('E', 'Empresa'), ('F', 'Fornecedor')], default='I', help_text='Tipo de conta a ser criada', max_length=1, verbose_name='Tipo'),
        ),
    ]
